# Generated by Django 6.0.4 on 2026-05-20 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofile_address_alter_userprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('pet_type', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=20)),
                ('breed', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('vaccines', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('Salud estable', 'Salud estable'), ('Seguimiento preventivo', 'Seguimiento preventivo'), ('Requiere atención', 'Requiere atención')], max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
