# Generated by Django 6.0.4 on 2026-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment_servicereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
